#pragma warning(disable : 4996)
#include "src/types.h"
#include "src/utils.cpp"
#include "src/dictionary.cpp"
#include "src/params.cpp"
#include "src/settings.cpp"
#include "src/capture.cpp"
#include "src/pnp_obj.cpp"
#include "src/marker.cpp"
#include "src/frame.cpp"
#include "src/region_select.cpp"
#include "src/aruco_detection_impl.cpp"
#include "src/aruco_detection_setting.cpp"
#include "src/aruco_detection.cpp"
#include "src/record.cpp"
#include "src/viz_window.cpp"
#include "src/analysis.cpp"
#include "src/front.cpp"