
#include <iostream>
#include <unordered_map>
#include <queue>
#include <deque>
#include <cmath>
#include <chrono>
#include <list>
#include <time.h>
#include <math.h>
#include <algorithm>
#include <numeric>
#include <string>
#include <vector>
#include <filesystem>
#include <assert.h>
#include <thread>
#include <functional>
#include <map>
#include <math.h>
#include <sstream>
#include <stack>
#include <bitset>
#include <set>
#include <ranges>
#include <format>
#include <g2o/types/sba/types_six_dof_expmap.h>
#include <g2o/core/block_solver.h>
#include <g2o/core/optimization_algorithm_levenberg.h>
#include <g2o/core/robust_kernel_impl.h>
#include <g2o/solvers/csparse/linear_solver_csparse.h>
#include <g2o/solvers/dense/linear_solver_dense.h>
#include "g2o/types/sba/types_sba.h"
#include <g2o/core/factory.h>
#include <g2o/stuff/macros.h>
#include <Eigen/Geometry>
#include <Eigen/core>
#include <Eigen/Dense>
#include <Eigen/SVD>
#include <opencv2/core/core.hpp>
#include <opencv2/core/eigen.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/calib3d.hpp>
#include <opencv2/core/matx.hpp>
#include <opencv2/viz.hpp>
#include <json/json.h>
#include <fstream>


